AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for CICD pull request event'

#Declaring input parameters, parameter type, default value and allowed values of the parameter
Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

#Resource provisioning
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 
        Fn::Sub: '${AWS::StackName}-${Environment}-bucket'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: GithubActionTesting

  # Outputs:
  #   S3BucketName:
  #     Value: !GetAtt
  #       - MyS3Bucket
  #     Description: Name of hosted S3 bucket
  