name: Delete S3 bucket stack on merge 

#trigger event for the github action workflowv to initiate
on:
  pull_request:
    types:
      - closed
    paths:
      - 'cloudformation/**'


jobs:  
 #Cleanup after merge
  cleanup-on-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1

      - name: Delete Test Stack
        run: |
          stack_name=nilaj-pr-test-stack-${{github.event.pull_request.number}}
          aws cloudformation delete-stack --stack-name ${stack_name}